#########################################################################################
##  DEPLOY TO AZURE STATIC WEB APP
#########################################################################################
name: Azure Static Web Apps CI/CD

#########################################################################################
##  WORKFLOW TRIGGER
#########################################################################################
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

#########################################################################################
##  WORKFLOW JOBS
#########################################################################################
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    environment:
      name: deployment
      url: ${{ vars.SITE_URL }}
    outputs:
      PACKAGE_VERSION: ${{ steps.version.outputs.PACKAGE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version Number
        id: version
        run: |
          packageVersion="v$(npm pkg get version | sed 's/"//g')"
          echo "package version: $packageVersion"
          echo "PACKAGE_VERSION=$packageVersion" >> $GITHUB_OUTPUT

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_FLOWER_0E59B2C0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          output_location: "dist/eslutz.github.io" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      - name: Create Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: `${{ steps.version.outputs.PACKAGE_VERSION }}`,
                target_commitish: context.sha,
                name: `Release ${{ steps.version.outputs.PACKAGE_VERSION }}`,
                draft: false,
                prerelease: false,
                generate_release_notes: true,
              });
            } catch (error) {
              if (error.status === 422) {
                console.log('Release already exists.');
              } else {
                core.setFailed(error.message);
              }
            }

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_FLOWER_0E59B2C0F }}
          action: "close"
